### PR TITLE
In dbWriteTable change parameter name from fieldTypes to field.types …

### PR DESCRIPTION
**Pull request by jschelbert**
…to be consistent with the DBI package

### CODE REVIEW

**Comment by jschelbert** [comment]
The DBI man page for dbWriteTable states
> The field.types argument must be a named character vector with at most one entry for each column. It indicates the SQL data type to be used for a new column.

sqlCreateTable has the additional argument "fieldTypes" in odbc (since 1.1.0).
How should consistency be done between DBI dbWriteTable (with _field.types_) and odbc sqlCreateTable (with _fieldTypes_)?

**Comment by jimhester** [comment]
Yes you are correct this should be `field.types` to match the spec. Could you adjust `sqlCreateTable` accordingly as well?

**Comment by jimhester** [comment]
And add a note to NEWS.md with this change, referencing this PR # and your GitHub handle?

**Comment by jschelbert** [comment]
Sure thing, here you go. Keep up the good work :thumbsup:

**Pull request merged**
