### PR TITLE
Add custom `sqlCreateTable` and `dbListTables` method for Taradata connections 

### PR DESCRIPTION
**Pull request by edgararuiz**

### CODE REVIEW

**Comment by jimhester** [comment]
You need to modify the namespace / documentation manually, I'll handle it.

**Comment by edgararuiz** [comment]
Awesome, thanks!

**Comment by hoxo-m** [comment]
Excellent!
It works fine in my environment.

**Comment by nwstephens** [comment]
This pull request is not working for me. When I attempt a connection to Teradata I get the error: ```Error in new(info$dbms.name, ptr = ptr, quote = quote, info = info, encoding = encoding) : trying to generate an object from a virtual class ("Teradata")``` When I try to connect to Teradata with Edgar's branch, I succeed. Is there a reason Edgar's branch work, but the merged branch does not?

**Comment by jimhester** [comment]
Sorry @nwstephens, fixed by https://github.com/rstats-db/odbc/commit/713e9ddf332b7c670dd723dd321720a4f749196c

**Comment by nwstephens** [comment]
@jimhester Odd. Now I'm getting this error:
```Error in assignClassDef(Class, classDef, where) : 
  class “Teradata” has a locked definition in package ‘odbc’```

**Comment by jimhester** [comment]
Ok That should be fixed now (b3d159a)

**Pull request merged**
